---
version: "3.5"

services:
  neo4j-server:
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_connector_http_advertised__address=localhost:7474
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
      - NEO4J_dbms_default__advertised__address=localhost
    image: "neo4j:latest"
    volumes:
      - ./db-seed:/db-seed
    ports: 
      - 7473-7474:7473-7474
      - 7687:7687
